# Generated by Django 4.0.4 on 2022-05-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='core.condominio', verbose_name='Condominio'),
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=200, verbose_name='RUT')),
                ('inicio', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='core.condominio', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'facultad',
                'verbose_name_plural': 'facultades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=200, verbose_name='RUT')),
                ('calidad', models.CharField(choices=[('P', 'Presidente'), ('T', 'Tesorero'), ('S', 'Secretario'), ('O', 'Otro')], max_length=1)),
                ('inicio', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comites', to='core.condominio', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'comite',
                'verbose_name_plural': 'comités',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=200, verbose_name='RUT')),
                ('inicio', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='core.condominio', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=200, verbose_name='Comentarios')),
                ('tipo', models.CharField(choices=[('AO', 'Asamblea Ordinaria'), ('AEA', 'Asamblea Extraordinaria de Mayoría Absoluta'), ('AER', 'Asamblea Extraordinaria de Mayoría Reforzada'), ('RC', 'Reunión de Comité'), ('D', 'Documento'), ('O', 'Otro')], max_length=3)),
                ('fecha', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='core.condominio', verbose_name='Condominio')),
            ],
            options={
                'verbose_name': 'acta',
                'verbose_name_plural': 'actas',
                'ordering': ['-created'],
            },
        ),
    ]
