# Generated by Django 4.0.4 on 2022-05-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tarea_condominio_facultades_comite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administradores',
            new_name='Administrador',
        ),
        migrations.RenameModel(
            old_name='Facultades',
            new_name='Facultad',
        ),
    ]
