# Generated by Django 4.0.4 on 2022-05-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_administradores_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominio',
            old_name='administrador',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='acta',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio', verbose_name='Condominio'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio', verbose_name='Condominio'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio', verbose_name='Condominio'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.condominio', verbose_name='Condominio'),
        ),
    ]
