# Generated by Django 4.0.4 on 2022-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_administrador_condominio_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='calidad',
            field=models.CharField(blank=True, choices=[('P', 'Presidente'), ('T', 'Tesorero'), ('S', 'Secretario'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comite',
            name='inicio',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='comite',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='rut',
            field=models.CharField(blank=True, max_length=200, verbose_name='RUT'),
        ),
    ]
