# Generated by Django 4.0.4 on 2022-05-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comite_calidad_alter_comite_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='rut',
            field=models.CharField(max_length=200, verbose_name='RUT'),
        ),
    ]
