# Generated by Django 4.0.4 on 2022-05-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_comite_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automatizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanzador', models.CharField(blank=True, choices=[('C', 'Se completa tarea'), ('A', 'Se archiva tarea'), ('E', 'Se elimina tarea'), ('N', 'Se crea tarea nueva tarea')], max_length=1)),
                ('codigo', models.CharField(max_length=200, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('efecto', models.CharField(blank=True, choices=[('A', 'Crear una nueva tarea'), ('C', 'Enviar correo electrónico'), ('E', 'Se elimina tarea'), ('N', 'Se crea tarea nueva tarea')], max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'automatizacion',
                'verbose_name_plural': 'automatizaciones',
                'ordering': ['-created'],
            },
        ),
    ]
