# Generated by Django 4.0.4 on 2022-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_automatizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatizacion',
            name='efecto',
            field=models.CharField(blank=True, choices=[('C', 'Crear una nueva tarea'), ('C', 'Enviar correo electrónico')], max_length=1),
        ),
    ]
